import { Component } from '@angular/core';
import { APP_ROOT, APP_ROOT_AFFECTATION_CAISSIER_CAISSE_JOURNAL, 
  APP_ROOT_CAISSE_CAISSE_JOURNAL, APP_ROOT_CENTRE_ANALYTIQUE_DONNEE_BASE, 
  APP_ROOT_JOURNAL_CAISSE_JOURNAL, APP_ROOT_NATURE_OPERATION_DONNEE_BASE, 
  APP_ROOT_OPERATION_GENERAL, 
  APP_ROOT_TAUX_DONNEE_BASE, APP_ROOT_TIERS_DONNEE_BASE,
  APP_ROOT_PLAN_COMPTABLE_DONNEE_BASE, APP_ROOT_BUDGETS_BUDGET, APP_ROOT_BUDGETS_LIGNE_BUDGET,
  APP_ROOT_DMD_DECAISSEMENT, APP_ROOT_DONNEE_BASE_DEVISE, APP_ROOT_STRUCTURE_DEPARTEMENT, APP_ROOT_STRUCTURE_SITE, APP_ROOT_ADMINISTRATION, APP_STRUCTURE_SOCIETE, 
  APP_ROOT_ADMINISTRATION_USER,
  APP_ROOT_AFF_NATURE_CENTRE_DONNEE_BASE, APP_AFF_DEPT_NATURE_DONNEE_BASE} from '../../../_core/routes/frontend.root';
import { RouterLink, RouterModule, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-layout-menu',
  imports: [RouterLink, RouterModule],
  templateUrl: './layout-menu.component.html',
  styleUrl: './layout-menu.component.css',
})
export class LayoutMenuComponent {
  root_taux = APP_ROOT_TAUX_DONNEE_BASE;
  root_journal = APP_ROOT_JOURNAL_CAISSE_JOURNAL;
  root_caisse = APP_ROOT_CAISSE_CAISSE_JOURNAL;
  root_affectation_caissier = APP_ROOT_AFFECTATION_CAISSIER_CAISSE_JOURNAL;
  root_operation = APP_ROOT_OPERATION_GENERAL;
  root_tiers = APP_ROOT_TIERS_DONNEE_BASE;
  root_centre_analytique = APP_ROOT_CENTRE_ANALYTIQUE_DONNEE_BASE;
  root_plan_comptable = APP_ROOT_PLAN_COMPTABLE_DONNEE_BASE;
  root_nature_operation = APP_ROOT_NATURE_OPERATION_DONNEE_BASE;
  root_aff_nature_centre = APP_ROOT_AFF_NATURE_CENTRE_DONNEE_BASE;
  root_aff_dept_nature = APP_AFF_DEPT_NATURE_DONNEE_BASE;
  root = APP_ROOT;
  root_budget = APP_ROOT_BUDGETS_BUDGET;
  root_ligne_budget = APP_ROOT_BUDGETS_LIGNE_BUDGET;
  root_demande_decaissement = APP_ROOT_DMD_DECAISSEMENT;
  root_societe = APP_STRUCTURE_SOCIETE;
  root_devise = APP_ROOT_DONNEE_BASE_DEVISE;
  root_utilisateur = APP_ROOT_ADMINISTRATION_USER;
  root_site = APP_ROOT_STRUCTURE_SITE;
  root_departement = APP_ROOT_STRUCTURE_DEPARTEMENT;
}
